### ISSUE TITLE
Epic: The basic, free and open-souce version of the plugin

### ISSUE THREAD

**Issue by dawidurbanski** [wpappointments/wpappointments#39]
### What

List of items needed to be completed in order to make our first demo releasable.

### Features

- [x] First iteration of very simple email notifications
    - [x] https://github.com/wpappointments/wpappointments/issues/115
    - [x] #43 
    - [x] https://github.com/wpappointments/wpappointments/issues/139
- [x] Booking flow
    - [x] #45 
- [x] Settings page overhaul
    - [x] #46 
    - [x] https://github.com/wpappointments/wpappointments/issues/140
- [x] Admin dashboard overhaul
    - [x] https://github.com/wpappointments/wpappointments/issues/108
    - [x] https://github.com/wpappointments/wpappointments/issues/109
- [x] Flow block improvements
    - [x] https://github.com/wpappointments/wpappointments/issues/110
    - [x] https://github.com/wpappointments/wpappointments/issues/111
    - [x] https://github.com/wpappointments/wpappointments/issues/112
    - [x] https://github.com/wpappointments/wpappointments/issues/113
    - [x] https://github.com/wpappointments/wpappointments/issues/114
    - [x] https://github.com/wpappointments/wpappointments/issues/119
    - [x] https://github.com/wpappointments/wpappointments/issues/125
    - [x] https://github.com/wpappointments/wpappointments/issues/128
- [x] Calendar, dates and time
    - [x] https://github.com/wpappointments/wpappointments/issues/131
    - [x] https://github.com/wpappointments/wpappointments/issues/132
    - [x] https://github.com/wpappointments/wpappointments/issues/133
- [x] Other
    - [x] https://github.com/wpappointments/wpappointments/issues/145
    - [x] #120 
    - [x] https://github.com/wpappointments/wpappointments/issues/157
    - [x] https://github.com/wpappointments/wpappointments/issues/163
    - [x] https://github.com/wpappointments/wpappointments/issues/152
    - [x] https://github.com/wpappointments/wpappointments/issues/166
    - [x] https://github.com/wpappointments/wpappointments/issues/173
    - [x] https://github.com/wpappointments/wpappointments/issues/176
    - [x] https://github.com/wpappointments/wpappointments/issues/177

### Bugs

- [x] https://github.com/wpappointments/wpappointments/issues/135
- [x] https://github.com/wpappointments/wpappointments/issues/142
- [x] https://github.com/wpappointments/wpappointments/issues/143
- [x] https://github.com/wpappointments/wpappointments/issues/144
- [x] https://github.com/wpappointments/wpappointments/issues/151
- [x] https://github.com/wpappointments/wpappointments/issues/162
- [x] https://github.com/wpappointments/wpappointments/issues/168
- [x] https://github.com/wpappointments/wpappointments/issues/175

### After completion, we want to:

- [ ] Make latest plugin zip
- [ ] Prepare InstaWP environment
- [x] Feedback form admin dashboard
- [x] Make simple mu-plugin adding big banner to dashboard with activation button
- [ ] Make screencast with demo plugin walkthrough
- [x] Make updates to https://wpappointments.com
- [ ] Send info to users in the waiting list
- [ ] Prepare social media posts
